### ISSUE TITLE
Usecase missing: friend's 3ds has more friends

### ISSUE THREAD

**Issue by A7F** [Marenthyu/3dsSeedMinerGuide#13]
I think in Section One there should be an use case when the friend's 3ds has more friends added to its list. In this case, you won't get any movable_part1.sed but seedstarter extracts all the movables from all the friends tagging them with the relative friend code; you need to pick the right one and rename it as movable_part1 (thus, you have to remove target friend code from the file name).

If you want I can try to add it, as well as issue #12

**Comment by Marenthyu** [comment]
That was a one-line fix. Feel free to PR for #12
